@HOST=http://localhost:3000
@API-KEY=RG3TG6Z-DAZMWTQ-NJ2N6QG-WWE5NZE


### Change Password
POST {{HOST}}/api/auth/change-password
x-api-key: {{API-KEY}}
Content-Type: application/json

{
  "username": "demo",
  "password": "demo"
}

