@HOST=http://localhost:3000
@ENDPONT=claim
@API-KEY=RG3TG6Z-DAZMWTQ-NJ2N6QG-WWE5NZE
@CID=

### API ส่งข้อมูลการใช้บริการ DMHT ในการเคลม OPD
POST {{HOST}}/api/v1/opd/service-admissions/dmht?endpoint={{ENDPONT}}
x-api-key: {{API-KEY}}

