@HOST=http://localhost:3000
@ENDPONT=epidem
@API-KEY=RG3TG6Z-DAZMWTQ-NJ2N6QG-WWE5NZE
@CID=

### SendEPIDEM
POST {{HOST}}/api/SendEPIDEM?endpoint={{ENDPONT}}
x-api-key: {{API-KEY}}

### LookupTable
GET {{HOST}}/api/LookupTable?endpoint={{ENDPONT}}
x-api-key: {{API-KEY}}