version: '2.4'

services:
  moph-c19-proxy:
    container_name: moph-c19-proxy
    build:
      context: .
      dockerfile: ./Dockerfile
    image: registry.opensource-technology.com/moph-c19-proxy:${IMAGE_TAG:-latest}
    ports:
      - '${MOPHPROXY_PORT:-9090}:3000'
    env_file:
      - moph-c19-proxy.env
    environment:
      - TZ=Asia/Bangkok
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - authorized_key:/app/.authorized_key
    networks:
      - webproxy
      - moph-proxy-backend

volumes:
  authorized_key:

networks:
  webproxy:
    external: true
