version: '2.4'

services:
  moph-ic-proxy:
    container_name: moph-ic-proxy
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/somprasongd/moph-ic-proxy:${IMAGE_TAG:-latest}
    ports:
      - '${MOPHPROXY_PORT:-9090}:3000'
    env_file:
      - moph-ic-proxy.env
    environment:
      - TZ=Asia/Bangkok
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - authorized_key:/app/.authorized_key
    depends_on:
      - redis
    networks:
      - webproxy
      - moph-proxy-backend

volumes:
  authorized_key:

networks:
  webproxy:
    external: true
